name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=5s --health-retries=5
        ports:
          - 5432:5432
      redis:
        image: redis:7
        options: >-
          --health-cmd="redis-cli ping" --health-interval=5s --health-retries=5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.9.0'
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run tests
        run: poetry run pytest -q
